### ISSUE TITLE
[Feat] 예약 번호 추가

### ISSUE THREAD

**Issue by tjdckscert** [DEU-Smiley/Smiley-BackEnd#137]
## 📝 Description
- Booking 테이블에 예약 번호를 추가한다.

## 📍 Todo
- [ ] Booking Entity 수정
- [ ] 예약 번호 만드는 기능 추가

**Comment by dongx0915** [comment]
PR 올리기 전이라 여기에 남김

아래 코드에서 hashCode로 랜덤 문자열 생성하는데 UUID를 그냥 잘라서 쓰는게 더 나아보임

```java
    public String bookingNumber() {
        String uuid = UUID.randomUUID().toString().replace("-","");
        if (uuid.hashCode()<0) uuid = "S"+Math.abs(uuid.hashCode());
        else uuid = "M"+Math.abs(uuid.hashCode());
        return uuid;
    }
```

아래는 GPT 피셜

UUID.randomUUID()의 값을 7자리로 직접 잘라서 사용하는 것과 위의 코드 (hashCode()를 사용하는 것) 사이에서 안정성을 비교하면 다음과 같은 분석이 가능합니다:

### UUID의 7자리 사용:

- UUID.randomUUID()는 보통 매우 랜덤한 값을 생성합니다.
- 직접 7자리를 잘라서 사용할 경우, UUID의 특정 부분만을 선택하여 사용하게 됩니다. UUID의 앞부분이나 뒷부분 중 어느 부분이 더 랜덤하다고 확정적으로 말할 수는 없지만, 전체적으로는 높은 랜덤성을 기대할 수 있습니다.
- 중복의 가능성이 있지만, 매우 낮습니다.

### UUID의 hashCode() 사용:
- hashCode()의 반환값은 32비트 정수로, 전체 UUID 공간을 표현하기에는 제한적입니다. 따라서 여러 다른 UUID 값이 동일한 해시 코드를 가질 수 있습니다 (해시 충돌).
- hashCode()는 객체의 빠른 동일성 확인을 위한 것이며, 고도의 랜덤성을 기대하기는 어렵습니다.
- hashCode()를 사용할 경우, 예약 번호의 중복 가능성이 상대적으로 높아집니다.


### 결론:
- UUID.randomUUID()에서 직접 7자리를 잘라서 사용하는 것이 hashCode()를 사용하는 것보다 더 안정적입니다. 해시 충돌의 가능성이 상대적으로 높은 hashCode()를 사용하는 방식보다 UUID의 일부를 사용하는 방식이 더 높은 랜덤성을 제공하며 중복 위험도 낮춥니다.
